# Natural Language Processing (NLP) Assignment
This assignment will guide you through the basic concepts of Natural Language Processing including:
- Text preprocessing
- Tokenization and N-grams
- Named Entity Recognition (NER)
- Converting text into numbers (vectorization)
- Word embeddings (for experienced learners)

You can run and modify the code cells below to complete the tasks.

In [3]:
!pip install nltk spacy matplotlib wordcloud numpy pandas

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.1 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.1 MB 1.2 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.1 MB 1.3 MB/s eta 0:00:05
   --------- ------------------------------ 1.8/8.1 MB 1.3 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.1 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 2.6/8.1 MB 1.5 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.1 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 3

In [15]:
# Import required libraries
import nltk
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import numpy as np
import pandas as pd
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import ngrams
nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
import nltk

# Force redownload of punkt in case of corruption
nltk.download('punkt', force=True)
nltk.download('stopwords', force=True)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

## 1. Text Preprocessing
Clean the following text by converting it to lowercase, removing punctuation and stop words.

In [18]:
!python -m nltk.downloader punkt_tab

c:\Users\Beza\anaconda3\envs\medibot\lib\runpy.py:126: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Beza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


In [19]:
# Import required libraries
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download required NLTK resources
try:
    nltk.download('punkt', quiet=True)
    nltk.download('stopwords', quiet=True)
except Exception as e:
    print(f"Error downloading NLTK resources: {e}")
    nltk.download('punkt')
    nltk.download('stopwords')

# Sample text
text = "Natural Language Processing is a fascinating field. It combines linguistics and computer science!"

# Preprocess function
def preprocess(text):
    # Convert to lowercase
    text = text.lower()
    
    # Tokenize
    tokens = word_tokenize(text)
    
    # Remove punctuation and stopwords
    stop_words = set(stopwords.words('english'))
    cleaned_tokens = [token for token in tokens if token not in string.punctuation and token not in stop_words]
    
    return cleaned_tokens

# Print cleaned tokens
try:
    cleaned_tokens = preprocess(text)
    print(cleaned_tokens)
except LookupError as e:
    print(f"LookupError: {e}")
    print("Attempting to download required NLTK resources...")
    nltk.download('punkt')
    nltk.download('stopwords')
    cleaned_tokens = preprocess(text)
    print(cleaned_tokens)

['natural', 'language', 'processing', 'fascinating', 'field', 'combines', 'linguistics', 'computer', 'science']


## 2. Tokenization and N-grams
Generate bigrams (2-grams) from the cleaned tokens.

In [ ]:
def preprocess(text):
    doc = nlp(text.lower())
    cleaned_tokens = [token.text for token in doc if token.is_alpha and token.text not in stop_words]
    return cleaned_tokens

# Clean the text
cleaned_tokens = preprocess(text)
print("Cleaned Tokens:", cleaned_tokens)

# Generate bigrams from cleaned tokens
bigrams = list(ngrams(cleaned_tokens, 2))
print("Bigrams:", bigrams)

Cleaned Tokens: ['natural', 'language', 'processing', 'fascinating', 'field', 'combines', 'linguistics', 'computer', 'science']
Bigrams: [('natural', 'language'), ('language', 'processing'), ('processing', 'fascinating'), ('fascinating', 'field'), ('field', 'combines'), ('combines', 'linguistics'), ('linguistics', 'computer'), ('computer', 'science')]


## 3. Named Entity Recognition (NER)
Use spaCy to perform NER on a new sentence.

In [ ]:
# Example sentence
sentence = "Barack Obama was born in Hawaii and was elected president in 2008."
doc = nlp(sentence)
for ent in doc.ents:
    print(ent.text, ent.label_)

Barack Obama PERSON
Hawaii GPE
2008 DATE


## 4. Converting Text to Numbers
Use CountVectorizer and TfidfVectorizer to convert a list of sentences into numeric vectors.

In [ ]:
sentences = [
    "I love machine learning.",
    "Natural language processing is a part of AI.",
    "AI is the future."
]

# CountVectorizer
count_vec = CountVectorizer()
X_count = count_vec.fit_transform(sentences)
print("Count Vectorizer Output:\n", X_count.toarray())

# TfidfVectorizer
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(sentences)
print("\nTF-IDF Vectorizer Output:\n", X_tfidf.toarray())

Count Vectorizer Output:
 [[0 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 1 0 0 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 0 0 0 0 1]]

TF-IDF Vectorizer Output:
 [[0.         0.         0.         0.         0.57735027 0.57735027
  0.57735027 0.         0.         0.         0.         0.        ]
 [0.30650422 0.         0.30650422 0.40301621 0.         0.
  0.         0.40301621 0.40301621 0.40301621 0.40301621 0.        ]
 [0.42804604 0.5628291  0.42804604 0.         0.         0.
  0.         0.         0.         0.         0.         0.5628291 ]]


## 5. Word Embeddings (Advanced)
Use spaCy to get word vectors (embeddings) for given words.

In [21]:
# Note: en_core_web_sm does not have word vectors. You can install and use en_core_web_md
# Uncomment below to install and load the medium model if needed.
!python -m spacy download en_core_web_md
nlp = spacy.load("en_core_web_md")

# Example word vector
word = nlp("machine")[0]
print("Vector for 'machine':\n", word.vector)

     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
      --------------------------------------- 0.5/33.5 MB 1.5 MB/s eta 0:00:22
     - -------------------------------------- 1.3/33.5 MB 2.6 MB/s eta 0:00:13
     -- ------------------------------------- 2.1/33.5 MB 3.0 MB/s eta 0:00:11
     --- ------------------------------------ 2.9/33.5 MB 3.3 MB/s eta 0:00:10
     ---- ----------------------------------- 3.9/33.5 MB 3.5 MB/s eta 0:00:09
     ----- ---------------------------------- 4.7/33.5 MB 3.6 MB/s eta 0:00:09
     ------ --------------------------------- 5.5/33.5 MB 3.6 MB/s eta 0:00:08
     ------- -------------------------------- 6.6/33.5 MB 3.7 MB/s eta 0:00:08
     ---